### ISSUE TITLE
[ansible] using inventory-file (-) as alias parameter breaks parser

### ISSUE THREAD

**Issue by vikrantpogula** [StackStorm/st2contrib#335]
Stack trace (/var/log/st2/st2api.log)

```
API call failed: bad character in group name u'inventory-file'#012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 631, in __call__#012    self.invoke_controller(controller, args, kwargs, state)#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller#012    result = controller(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 230, in callfunction#012    result = f(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 78, in post#012    param_stream=command)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 123, in _extract_parameters#012    return parser.get_extracted_param_value()#012  File "/usr/lib/python2.7/dist-packages/st2common/models/utils/action_alias_utils.py", line 80, in get_extracted_param_value#012    matched_stream = re.match(reg, self._param_stream, re.DOTALL)#012  File "/usr/lib/python2.7/re.py", line 137, in match#012    return _compile(pattern, flags).match(string)#012  File "/usr/lib/python2.7/re.py", line 244, in _compile#012    raise error, v # invalid expression#012error: bad character in group name u'inventory-file'
2015-12-10T01:03:34.362035+00:00 localhost st2api[4932]: ERROR 140361395123536 [-] Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 631, in __call__#012    self.invoke_controller(controller, args, kwargs, state)#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller#012    result = controller(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 230, in callfunction#012    result = f(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 78, in post#012    param_stream=command)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 123, in _extract_parameters#012    return parser.get_extracted_param_value()#012  File "/usr/lib/python2.7/dist-packages/st2common/models/utils/action_alias_utils.py", line 80, in get_extracted_param_value#012    matched_stream = re.match(reg, self._param_stream, re.DOTALL)#012  File "/usr/lib/python2.7/re.py", line 137, in match#012    return _compile(pattern, flags).match(string)#012  File "/usr/lib/python2.7/re.py", line 244, in _compile#012    raise error, v # invalid expression#012error: bad character in group name u'inventory-file'#012Traceback (most recent call last):#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 631, in __call__#012    self.invoke_controller(controller, args, kwargs, state)#012  File "/usr/local/lib/python2.7/dist-packages/pecan/core.py", line 531, in invoke_controller#012    result = controller(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2common/models/api/base.py", line 230, in callfunction#012    result = f(*args, **kwargs)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 78, in post#012    param_stream=command)#012  File "/usr/lib/python2.7/dist-packages/st2api/controllers/v1/aliasexecution.py", line 123, in _extract_parameters#012    return parser.get_extracted_param_value()#012
```

**Comment by vikrantpogula** [comment]
moved to https://github.com/StackStorm/st2/issues/2280
