### ISSUE TITLE
AWS pack is not working

### ISSUE THREAD

**Issue by jmound** [StackStorm/st2contrib#357]
Installed the pack and tried a few actions, all failing with:
```
AttributeError: 'NoneType' object has no attribute ACTION_NAME
```
Example:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/aws/actions/run.py", line 18, in run
    return self.do_method(module_path, cls, action, **kwargs)
  File "/opt/stackstorm/packs/aws/actions/lib/action.py", line 87, in do_method
    resultset = getattr(obj, action)(**kwargs)
AttributeError: 'NoneType' object has no attribute 'get_all_instances'
```

**Comment by DoriftoShoes** [comment]
Thanks for the report!  It looks like the connection object isn't getting instantiated correctly and we are missing some error handling around that.  I'll try and repro on my end.  Did you add your key and secret key to config.yaml in the aws pack?

**Comment by jmound** [comment]
No, the Stackstorm instance has an assigned IAM role which grants it permissions. 
```
aws ec2 --region us-east-1 describe-instances
```
from the CLI works as expected.  I'll try again with a configured config.yaml.

**Comment by lakshmi-kannan** [comment]
Closing. Please reopen if needed again!
