### ISSUE TITLE
hubot pack install problem

### ISSUE THREAD

**Issue by minhdanh** [StackStorm/st2contrib#421]
In install some packs, including hubot:

`st2 run packs.install packs=aws,slack,email,hubot,jenkins repo_url=https://github.com/StackStorm/st2contrib.git`

It failed for hubot. Here's the output:

```
............
id: 56d6bfc4326fe918a9e018cb
action.ref: packs.install
parameters: 
  packs:
  - aws
  - slack
  - email
  - hubot
  - jenkins
  repo_url: https://github.com/StackStorm/st2contrib.git
status: failed
error: st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "hubot"
st2.actions.python.SetupVirtualEnvironmentAction: INFO     Virtualenv path "/opt/stackstorm/virtualenvs/hubot" doesn't exist
st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "hubot" in "/opt/stackstorm/virtualenvs/hubot"
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 116, in <module>
    obj.run()
  File "/usr/lib/python2.7/dist-packages/st2actions/runners/python_action_wrapper.py", line 61, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 60, in run
    self._setup_pack_virtualenv(pack_name=pack_name, update=update)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 102, in _setup_pack_virtualenv
    self._create_virtualenv(virtualenv_path=virtualenv_path)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 135, in _create_virtualenv
    raise Exception('Virtualenv binary "%s" doesn't exist.' % (virtualenv_binary))
Exception: Virtualenv binary "/usr/bin/virtualenv" doesn't exist.

traceback: None
failed_on: setup_virtualenv
start_timestamp: 2016-03-02T10:26:12.571667Z
end_timestamp: 2016-03-02T10:26:35.313739Z
+--------------------------+-----------+-------------------+-------------------------+-------------------------------+
| id                       | status    | task              | action                  | start_timestamp               |
+--------------------------+-----------+-------------------+-------------------------+-------------------------------+
| 56d6bfc4326fe918a57a42c8 | succeeded | download          | packs.download          | Wed, 02 Mar 2016 10:26:12 UTC |
| 56d6bfd9326fe918a57a42ca | succeeded | virtualenv_prerun | packs.virtualenv_prerun | Wed, 02 Mar 2016 10:26:33 UTC |
| 56d6bfda326fe918a57a42cc | failed    | setup_virtualenv  | packs.setup_virtualenv  | Wed, 02 Mar 2016 10:26:34 UTC |
+--------------------------+-----------+-------------------+-------------------------+-------------------------------+
```

**Comment by minhdanh** [comment]
This failed for other pack too. After installing `virtualenv` manually, the installation succeeded. I installed St2 via Ansible, so there should be some update on the playbook.

**Comment by armab** [comment]
Recently we released brand new packages which have all necessary pip dependencies bult-in, including virtualenv.

The recommended (and now easiest) way of installing StackStorm is: 
* [`ubuntu trusty`, `debian wheezy`, `debian jessie`](https://docs.stackstorm.com/install/deb.html)
* [`RHEL7/CentOS7`](https://docs.stackstorm.com/install/rhel7.html)
* [`RHEL6/CentOS6`](https://docs.stackstorm.com/install/rhel6.html)

Please try! We'll be glad to hear if that works better for you.

-----

Because of big work related to new packages, Ansible provisioner is outdated and requires rewrite.
I'll update `st2-ansible` repo and include BC/Deprecation notice, until we stabilize everything during this transition.

Also, since it's really `st2-ansible` provisioner failed to install `virtualenv` dependency, I'm closing this issue in favor of: https://github.com/StackStorm/ansible-st2/issues/40

Thanks for the report, @minhdanh!
