### ISSUE TITLE
Elasticsearch Pack Doesn't Support ES 2.4

### ISSUE THREAD

**Issue by codyaray** [StackStorm/st2contrib#558]
Doesn't look like the Elasticsearch pack supports ES 2.x.

```
Expected Elasticsearch version range > 1.0.0 < 2.2.0
ERROR: Incompatible with version 2.4.0 of Elasticsearch.  Exiting.
```

When I tried upgrading the requirements.txt for `elasticsearch-curator` from 3.4.0 to 4.1.0 (latest), it looks like there have been some pretty large changes in the library's API.

```
Traceback (most recent call last):
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 179, in <module>
    obj.run()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 115, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/local/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 129, in _get_action_instance
    actions_cls = action_loader.register_plugin(Action, self._file_path)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/loader.py", line 148, in register_plugin
    module = importlib.import_module(module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/alldata/opt/stackstorm/packs/elasticsearch/actions/curator_runner.py", line 4, in <module>
    from lib.curator_action import CuratorAction
  File "/alldata/opt/stackstorm/packs/elasticsearch/actions/lib/curator_action.py", line 3, in <module>
    from curator_invoke import CuratorInvoke
  File "/alldata/opt/stackstorm/packs/elasticsearch/actions/lib/curator_invoke.py", line 3, in <module>
    from items_selector import ItemsSelector
  File "/alldata/opt/stackstorm/packs/elasticsearch/actions/lib/items_selector.py", line 3, in <module>
    from curator.api.utils import get_indices
ImportError: No module named api.utils
```

Likely related to the so-called [Massive rewrite of Curator for 4.0](https://github.com/elastic/curator/commit/a077918bd02d1069418d9e106283dabb3c49e4fb) ;)

**Comment by codyaray** [comment]
The `api` module was blown away and some of the classes migrated elsewhere. Some of these are easy to track down. 

```
* curator.api.utils.get_indices => curator.utils.get_indices
* curator.api.utils.get_snapshots => from curator.utils.get_snapshot
* curator.api.utils.get_version => curator.utils.get_version
* curator.api.utils.is_master_node => curator.utils.is_master_node
```

Haven't been able to find these though:

```
* curator.api.filter.apply_filter
* curator.api.filter.build_filter
* curator.api.utils.index_closed
```

I'm sure there's more as well.

**Comment by DoriftoShoes** [comment]
I'll dig in to this and get the pack updated.

**Comment by codyaray** [comment]
Any update here @DoriftoShoes ?

**Comment by LindsayHill** [comment]
Will track this against https://github.com/StackStorm-Exchange/stackstorm-elasticsearch/issues/5
