### ISSUE TITLE
Unable to run the st2 run sensu.check_list

### ISSUE THREAD

**Issue by voodemsanthosh** [StackStorm/st2contrib#638]
Trying to run **st2 run sensu.check_list** from stackstorm and getting below error.

$ st2 run sensu.check_list
..
id: 585239533915ecbc20eb71ea
status: failed
parameters: None
result:
  exit_code: 1
  result: None
  stderr: "Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/pytho                                                                                                                n_action_wrapper.py", line 211, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/pytho                                                                                                                n_action_wrapper.py", line 125, in run
    action = self._get_action_instance()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/pytho                                                                                                                n_action_wrapper.py", line 181, in _get_action_instance
    action_service=action_service)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/utils                                                                                                                .py", line 77, in get_action_class_instance
    action_instance = action_cls(**kwargs)
  File "/opt/stackstorm/packs/sensu/actions/lib/sensu.py", line 21, in __init__
    self.username = self.config['user']
KeyError: 'user'
"
  stdout: ''

And I have updated sensu.yaml(/opt/stackstorm/packs/sensu/)

# Sensu API connection info
host: "server where we installed the stackstorm"
port: "4567"
user: "server login userid"
pass: "installed server password"
ssl: false
 

Please let me know where is the issue.

**Comment by LindsayHill** [comment]
Follow step 2 in the README file (https://github.com/StackStorm-Exchange/stackstorm-sensu):

> Copy the example configuration in sensu.yaml.example to `/opt/stackstorm/configs/sensu.yaml`

The configuration file should be at `/opt/stackstorm/configs/sensu.yaml`
