### ISSUE TITLE
newrelic_get_alert issue

### ISSUE THREAD

**Issue by voodemsanthosh** [StackStorm/st2contrib#639]
Hey,

Running the newrelic_get_alert by providing app_name and getting below error,

Traceback (most recent call last):
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 211, in 
obj.run()
File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 126, in run
output = action.run(**self._parameters)
File "/opt/stackstorm/packs/newrelic/actions/get_alerts.py", line 24, in run
resp = requests.get(self.url, headers=self.headers, params=params).json()
File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 70, in get
return request('get', url, params=params, **kwargs)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 56, in request
return session.request(method=method, url=url, **kwargs)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
resp = self.send(prep, **send_kwargs)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
r = adapter.send(request, **kwargs)
File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

who do I configure SSL or do we have any chance to by pass the SSL?

Could you please provide the document to how to configure the new relic alerts to stackstorm.

Example:
I have a server configured in newrelic and if it is utilize X% CPU newrelic will generate the alert.

I need to send the same newrelic alert to stackstorm.

Please provide the sets and document to integrate newrelic alerts with stackstorm.

Thank you in advance.

**Comment by LindsayHill** [comment]
I thought that NewRelic only offered a SaaS solution, and there should be any SSL issues? What have you got configured for api_url? 

It sounds like you're running the action, but you probably want to configure the Sensor. Set up the sensor_config in `sensu.yaml`, and configure Newrelic to send webhook requests to the ST2 IP. That will give you triggers that you can then use in rules, to fire actions. 

What do you want to do with the Newrelic alert once it reaches StackStorm?

**Comment by voodemsanthosh** [comment]
we need to send the newrelic alerts to stackstorm by calling newrelic_get_alerts action. when I ran the action getting below error,
File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

for now I need to send the newrelic alerts to stackstrom server and newrelic_get_alerts.action should run success.

to avoid the ssl handshake failure do we have any bypass flag on this or what ssl cert is expecting here to  get the new relic alerts

**Comment by Kami** [comment]
Can you please gist the whole exception / error message (now it's not 100% obvious if they are using invalid cert - very unlikely / hostname mismatch because of a proxy / you don't have root CA certs on your system / similar).

If you are missing CA bundle, try installing `ca-certificates` package or similar depending on your distribution.

**Comment by voodemsanthosh** [comment]
Please find the full stacktrace,

Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 211, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 126, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/newrelic/actions/get_alerts.py", line 24, in run
    resp = requests.get(self.url, headers=self.headers, params=params).json()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)

**Comment by LindsayHill** [comment]
Ran some tests with current pack, not seeing any SSL certificate errors - suspect something site-local here, possibly related to MITM proxies, since api.newrelic.com does have a valid cert.
